const islamicQuizData = [
  {
    question: "How many pillars of Islam are there?",
    option1: "2",
    option2: "6",
    option3: "1",
    option4: "5",
    answer: "option4",
  },
  {
    question: "How many Pillars of Imaan?",
    option1: "10",
    option2: "6",
    option3: "4",
    option4: "8",
    answer: "option2",
  },
  {
    question: "Which prophet is known as the 'Father of Prophets'?",
    option1: "Musa AS",
    option2: "Isa AS",
    option3: "Ibrahim AS",
    option4: "Muhammad ﷺ",
    answer: "option3",
  },
  {
    question: "What scripture was given to the Prophet Muhammad ﷺ?",
    option1: "Torah",
    option2: "Bible",
    option3: "Quran",
    option4: "Zend-Avesta",
    answer: "option3",
  },
  {
    question: "During which month do Muslims fast from dawn to sunset?",
    option1: "Rajab",
    option2: "Sha'ban",
    option3: "Ramadan",
    option4: "Dhu al-Hijjah",
    answer: "option3",
  },

  {
    question: "Who was the first woman to accept Islam?",
    option1: "Aisha (RA)",
    option2: "Khadijah (RA)",
    option3: "Fatimah (RA)",
    option4: "Maryam (RA)",
    answer: "option2",
  },
  {
    question: "What is the last month of the Islamic calendar?",
    option1: "Dhu al-Qa'dah",
    option2: "Dhu al-Hijjah",
    option3: "Rajab",
    option4: "Sha'ban",
    answer: "option2",
  },
  {
    question:
      "Which companion of Prophet Muhammad (PBUH) is known as 'The Sword of Allah'?",
    option1: "Abu Bakr",
    option2: "Umar ibn Khattab",
    option3: "Ali ibn Abi Talib",
    option4: "Khalid ibn al-Walid",
    answer: "option4",
  },
  {
    question: "What does 'Sadaqah' mean in Islam?",
    option1: "Fasting",
    option2: "Charity",
    option3: "Pilgrimage",
    option4: "Prayer",
    answer: "option2",
  },
  {
    question:
      "Which prophet is mentioned in the Quran as having the ability to speak with animals?",
    option1: "Prophet Musa (Moses)",
    option2: "Prophet Isa (Jesus)",
    option3: "Prophet Sulaiman (Solomon)",
    option4: "Prophet Ibrahim (Abraham)",
    answer: "option3",
  },
  {
    question: "What is the significance of Laylat al-Qadr?",
    option1: "Night of the Ascension",
    option2: "Night of Power",
    option3: "Night of Forgiveness",
    option4: "Night of Miraj",
    answer: "option2",
  },
  {
    question:
      "What is the first revelation received by Prophet Muhammad (PBUH)?",
    option1: "Surah Al-Fatiha",
    option2: "Surah Al-Baqarah",
    option3: "Surah Al-Ikhlas",
    option4: "Surah Al-Alaq",
    answer: "option4",
  },
  {
    question: "In which city was the Prophet Muhammad (PBUH) born?",
    option1: "Makkah",
    option2: "Medina",
    option3: "Jerusalem",
    option4: "Cairo",
    answer: "option1",
  },
  {
    question: "In which year did the Prophet Muhammad migrate to Medina?",
    option1: "620 CE",
    option2: "622 CE",
    option3: "630 CE",
    option4: "632 CE",
    answer: "option2",
  },
  {
    question: "What is the migration known as",
    option1: "Nasr",
    option2: "Hijra",
    option3: "Change",
    option4: "Fath",
    answer: "option2",
  },
  {
    question: "Who are the best generations?",
    option1: "100 years ago",
    option2: "Ourselves",
    option3: "Sahaba, Tābi'ūn, Tabi' al-Tabi'in",
    option4: "Our parents",
    answer: "option3",
  },

  {
    question: "Does Imaan go up and down",
    option1: "Yes",
    option2: "No",
    option3: "Imaan is faith alone",
    option4: "Imaan is only a feeling",
    answer: "option1",
  },
  {
    question: "How many obligatory prayer do Muslims pray a day?",
    option1: "10",
    option2: "8",
    option3: "6",
    option4: "5",
    answer: "option4",
  },
  {
    question: "How many names does Allah have?",
    option1: "100",
    option2: "1",
    option3: "99",
    option4: "Not limited to 99",
    answer: "option4",
  },
  {
    question:
      " Out of the three categories of Tawheed (derived from the study and analysis of Qur'anic texts, of which there are many evidences for) which one is the most important and the one which Allaah requires of us?",
    option1: "Taweheed ar-Rubooiyyah",
    option2: "Tawheed Names and attributes",
    option3: "Tawheed al-Uloohiyah",
    option4: "I don't know",
    answer: "option3",
  },
  {
    question:
      "Rejecting khabar al-ahaad in aqidah was innovated by which sect?",
    option1: "Khawarij",
    option2: "Raafidah",
    option3: "Mu'tazilah",
    option4: "Ash'ariyyah",
    answer: "option3",
  },
  {
    question: "The length of the Day of Judgement is how many years?",
    option1: "1000",
    option2: "50,000",
    option3: "10,000",
    option4: "1",
    answer: "option2",
  },
  {
    question:
      "The two angels (Munkar and Nakeer) who will question the dead person will ask certain questions which are mentioned in which classical treatise?",
    option1: "Kashf ush-Shubuhaat",
    option2: "Al-Qawaa'id-ul-'Arba'ah",
    option3: " Thalaathat-ul-Usool",
    option4: " Nawaaqid-ul-Islaam",
    answer: "option3",
  },
  {
    question:
      "What is the ruling on celebrating the birthday of the Prophet Muhammad ﷺ?",
    option1: "It is good",
    option2: "It is your choice",
    option3: "It is an innovation and should not be done",
    option4: "It is an obligation",
    answer: "option3",
  },
  {
    question: "How should a Muslim act towards other people?",
    option1: "Horribly",
    option2: "Ignore them",
    option3: "Run away of them",
    option4: "Kidness and showing good manners",
    answer: "option4",
  },
  {
    question:
      "What is the prescribed charity for Muslims, typically amounting to 2.5% of their wealth?",
    option1: "Zakat",
    option2: "Sadaqah",
    option3: "Khums",
    option4: "Fitrah",
    answer: "option1",
  },

  {
    question:
      "Which pilgrimage is obligatory for every financially and physically able Muslim at least once in their lifetime?",
    option1: "Umrah",
    option2: "Hajj",
    option3: "Ziyarat",
    option4: "I'tikaf",
    answer: "option2",
  },
];

export default islamicQuizData;
